// <auto-generated />
using System;
using AttendanceControlBot.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AttendanceControlBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240117183017_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttendanceControlBot.Domain.Entity.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_number");

                    b.Property<int>("LessonDay")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_day");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_name");

                    b.Property<int>("LessonTime")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_time");

                    b.HasKey("Id");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("AttendanceControlBot.Domain.Entity.Parent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthId")
                        .HasColumnType("bigint")
                        .HasColumnName("auth_id");

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint")
                        .HasColumnName("chils_id");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stopped");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id");

                    b.ToTable("parents");
                });

            modelBuilder.Entity("AttendanceControlBot.Domain.Entity.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<long>("ParentAuthId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_auth_id");

                    b.HasKey("Id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("AttendanceControlBot.Domain.Entity.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_date");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<bool>("Signed")
                        .HasColumnType("boolean")
                        .HasColumnName("signed");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id");

                    b.ToTable("workers");
                });
#pragma warning restore 612, 618
        }
    }
}
